"""輸出語言(Obsidian 筆記標籤 + 分群提示)。--lang en|zh-TW,預設 en。"""
from __future__ import annotations

LABELS = {
    "en": {
        "contents": "Contents", "topic": "Topic", "phase": "Phase {n}",
        "asked": "Asked", "steps": "steps", "topics": "topics", "images": "images",
        "canvas": "Canvas:", "tool_only": "(tool calls only)", "other": "Other / unsorted",
        "idx_title": "Session Index",
        "idx_auto": "Auto-generated by `s2o index` — do not edit",
        "idx_recall": "**Recall**: find the relevant session here → open its note → "
                      "jump via Outline (or Obsidian search).",
        "idx_sessions": "sessions", "idx_topics": "topics",
    },
    "zh-TW": {
        "contents": "目錄", "topic": "主題", "phase": "第 {n} 段",
        "asked": "我問", "steps": "步", "topics": "主題", "images": "圖",
        "canvas": "節點圖見", "tool_only": "(僅工具操作)", "other": "其他 / 未分類",
        "idx_title": "Session 索引",
        "idx_auto": "自動產生(`s2o index`,別手改)",
        "idx_recall": "**recall 用法**:在這裡找到相關 session → 開該筆記 → "
                      "Outline 跳主題(或用 Obsidian 搜尋)。",
        "idx_sessions": "場", "idx_topics": "主題",
    },
}

LANGS = list(LABELS)
DEFAULT_LANG = "en"


def L(lang: str) -> dict:
    return LABELS.get(lang, LABELS[DEFAULT_LANG])


_RULES_COMMON = """你是對話主題分群器。輸入是一場 AI coding session 的步驟清單,每步有 intent(提問)、files(碰的檔名)、gist(助手首句)。把步驟分到幾條連貫主題,並給整場一個總標題。

規則(嚴格遵守):
1. 每步恰好歸一主題(不重不漏,所有 1..n 都要被分到)。
2. 一主題 = 一條連貫的問題/任務串。別碎到每步一主題;tiny(≤5 步同一事)→ 1 主題;大場(>50 步)可較多主題。
3. 主題【可非連續】:時間隔開但同一條線的步驟歸同一主題。
4. 複合提問【不拆】,整步歸主導/最主要那條線(看重心 + files + gist + 後續步接哪條線)。
5. files/gist 是消歧訊號:提問字面看不出時(如「這是連結」),用 files/gist 判斷屬哪條線。
7. 不要空主題。

只輸出一段 JSON(無 code fence、無其他文字):
{"title":"...","topics":[{"name":"...","steps":[1,2,3]}, ...]}
steps 用 1-based 原始步號。"""

_RULES_NAME = {
    "en": '6. 主題名與總標題請用「英文」:主題名簡短(≤6 words),總標題涵蓋全場(≤10 words);不可含 # [ ] | 與斜線。',
    "zh-TW": '6. 主題名簡短中文(≤16 字),總標題涵蓋全場(≤24 字);名稱與標題不可含 # [ ] | 與斜線。',
}


def cluster_rules(lang: str) -> str:
    name_rule = _RULES_NAME.get(lang, _RULES_NAME[DEFAULT_LANG])
    return _RULES_COMMON.replace("7. 不要空主題。", name_rule + "\n7. 不要空主題。")
